# Generated by Django 4.2.11 on 2024-05-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatPFE', '0001_initial'),
    ]

    operations = [
    ]
