# Generated by Django 4.2.11 on 2024-05-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChatPFE', '0002_auto_20240523_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('cin_enca', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password_enca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('cin_etud', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password_etud', models.CharField(max_length=255)),
            ],
        ),
    ]
