# Generated by Django 4.2.11 on 2024-05-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatPFE', '0003_initial'),
    ]

    operations = [
    
    ]
