# Generated by Django 4.2.11 on 2024-05-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatPFE', '0004_delete_responsable_administratif_responsable_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('cin', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('responsable_administratif', 'Responsable Administratif'), ('responsable', 'Responsable')], max_length=25)),
            ],
        ),
    ]
