# Generated by Django 4.2.11 on 2024-05-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatPFE', '0005_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification_Code',
            fields=[
                ('cin_verification', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
